name: Kodi addon checker on matrix

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Test with kodi-addon-checker on branch matrix
      run: |
        pip install kodi-addon-checker
        kodi-addon-checker --branch matrix .
